### ISSUE TITLE
Script completely broken

### ISSUE THREAD

**Issue by aurorarissime** [gazzamc/starfield_hex_updater#3] opened 2023-11-08 15:57 UTC
When I try to launch run.bat it opens a new Powershell window, only to close it almost instantly. Also, when I try to launch it manually by opening cli.ps1 by hand, it either throws errors at me and go back to the main menu, either some terms aren't recognized as a name of cmdlet, function, script file, or executable program

**Comment by gazzamc** [comment] 2023-11-08 16:10
The script isn't broken, as mentioned in the [README docs](https://github.com/gazzamc/starfield_hex_updater/tree/main/docs#auto-installer-gui), you need to change the `Execution Policy` of powershell.

Open powershell as admin and run the command below:

```
   Set-ExecutionPolicy Unrestricted 
```

Re-run the bat file and the window should remain open. Please report back with the results.

Note:
The error when opening `cli.ps1` is probably due to you opening it via `system32` and not the directory the script is located, the error is that it can't find the imported functions.

**Comment by aurorarissime** [comment] 2023-11-08 17:25
I already had the `Set-ExecutionPolicy Unrestricted` but still had the bug. But thanks to you, I managed to run properly `cli.ps1`. I'm currently trying to build it but it looks like it's struggling, trying to build sfse for tens of minutes after it threw an error during the patch step. I already had struggle with the build step, when I tried to build it manually, it wouldn't build `sfse_loader.exe`. Maybe it has the same problem, but I don't know why because after looking at the doc, it looks like I have every prerequisite :/

**Comment by aurorarissime** [comment] 2023-11-08 17:31
The error I get when it can't patch sfse : Patching SFSE
Traceback (most recent call last):mpleted. (Number of bytes processed: 5282424)                                      ]
  File "G:\SFSE\starfield_hex_updater\hex_updater.py", line 389, in <module>6)                                       ]
    main(sys.argv[1:])
  File "G:\SFSE\starfield_hex_updater\hex_updater.py", line 360, in main
    hex_dict = get_dict(dict_file_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\SFSE\starfield_hex_updater\hex_updater.py", line 136, in get_dict
    with open(r'{}'.format(path), 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

                Unsuccessfully Patched SFSE
Press Enter to continue...:

Edit : when I go in the SFSE category in the auto installer, I will get the patch error but it will still successfully build sfse. It won't move the file automatically also, but this I can move them myself.

Edit n°2 : the dll isn't builtusing the auto installer

**Comment by gazzamc** [comment] 2023-11-08 20:41
Can you attach the log file(s)?

Edit:

Did you install the dependencies manually? 

I've tested this on 3 seperate systems and many others have had no issues, it must either be a dependency issue or it's permissions.. The fact that the bat file doesn't start is a sign it might be permissions based. It won't build correctly among other things if the permissions are not correct. 

I would delete the sfse repo, and attempt to do all the steps in the script under the sfse option (not auto install).

**Comment by gazzamc** [comment] 2023-11-08 20:52
> 

> The error I get when it can't patch sfse : Patching SFSE Traceback (most recent call last):mpleted. (Number of bytes processed: 5282424) ] File "G:\SFSE\starfield_hex_updater\hex_updater.py", line 389, in 6) ] main(sys.argv[1:]) File "G:\SFSE\starfield_hex_updater\hex_updater.py", line 360, in main hex_dict = get_dict(dict_file_name) ^^^^^^^^^^^^^^^^^^^^^^^^ File "G:\SFSE\starfield_hex_updater\hex_updater.py", line 136, in get_dict with open(r'{}'.format(path), 'r') as file: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> ```
>             Unsuccessfully Patched SFSE
> ```
> 
> Press Enter to continue...:
> 
> Edit : when I go in the SFSE category in the auto installer, I will get the patch error but it will still successfully build sfse. It won't move the file automatically also, but this I can move them myself.
> 
> Edit n°2 : the dll isn't builtusing the auto installer

Are the dict files present under hex_tables folder? This error is saying it can't find the file that was passed.

**Comment by aurorarissime** [comment] 2023-11-08 21:38
Which log file do you need..? And where is it located please? And I already tried to build it manually, but ended up not having the exe built. I guess it's the permissions then, but I don't know which. On VSCommunity it looks like I have all of the necessary dependancies. And nope, there are only 3 jsons in the hex_tables folder.

**Comment by gazzamc** [comment] 2023-11-09 07:42
> Which log file do you need..? And where is it located please?

They should be generated under the logs folder within the repo folder eg. `starfield_hex_updater/logs`. If you can, all of them. It might be easier to zip the folder.

> And I already tried to build it manually, but ended up not having the exe built. I guess it's the permissions then, but I don't know which.

This seems very strange, did you manually try to build via visual studio or cmake? If cmake did you run it as admin?

> On VSCommunity it looks like I have all of the necessary dependancies

If you're not using visual studio for anything else, I'd suggest uninstalling it completely and allowing the script to install the compiler via chocolatey.

> And nope, there are only 3 jsons in the hex_tables folder.

That's correct, should be one for each version of the game to date.

Something you can try:

1. Set `Bypass Prompts` via the script options to `False` (so it doesn't return to menu after running something) 
2. Go to `Check Installed Dependencies` (Option 2)

Is it finding the compiler along with the vs install?

screen:
![image](https://github.com/gazzamc/starfield_hex_updater/assets/7975925/178729bf-63b1-4368-926a-e059850df0ec)

**Comment by aurorarissime** [comment] 2023-11-09 07:52
[logfile_2023.11.08_06.31.46.log](https://github.com/gazzamc/starfield_hex_updater/files/13305195/logfile_2023.11.08_06.31.46.log)
[logfile_2023.11.08_06.07.09.log](https://github.com/gazzamc/starfield_hex_updater/files/13305197/logfile_2023.11.08_06.07.09.log)
Here are the only files in the logs folder. Hope they're useful to you!

I tried via the cmake command. If to run cmake as admin you need to run the commnd in an admin powershell, I didn't tried that no. I will

I don't want to be annoying but how would I make installer the compiler via chocolatey.., I know what is it, but I don't know how to do it ^^'

And it looks like it's only finding the compiler, even though VS is installed 😶
![image](https://github.com/gazzamc/starfield_hex_updater/assets/121387740/880f3547-8892-44ef-8db5-ca220ddf5903)

If we can solve the problem it might be useful for anyone who might encounter the same problems as me, but I think I'll end up playing modded on Steam

**Comment by gazzamc** [comment] 2023-11-09 08:15
Ok looking at your logs, the issue is with the build. I don't think the files patched correctly, there seems to be a stray curly brace in `PluginManager.cpp`. 

As far as dependencies are concered it seems to be correct, but maybe VS17 C++ tools are not compatible. I might have missed it, but did you manage to get the bat file to run?

Can you try some things for me:

1. We'll try to re-build the sfse repo from scratch

> - Delete the `sfse` folder inside the `starfield_hex_updater` folder
> - Re-open the scripts and go to `SFSE` (Option 4)
> - - Follow the steps 1 - 3

Did it build? If not send me the log.

2. Ensure that the sfse repo is on the correct commit id

- Open a cmd or powershell (must be admin privs)
- cd to the `sfse` folder (eg. `starfield_hex_updater/sfse`)
- Run `git branch`
- You should see
![image](https://github.com/gazzamc/starfield_hex_updater/assets/7975925/f92e540b-f941-4bed-9163-d0cd5a9fcd42)


4. Install VS19 c++ tools

> - If you installed vs the traditional way (via exe), search for `Visual Studio Installer` in your start menu
> - Open it up and click modify
> ![image](https://github.com/gazzamc/starfield_hex_updater/assets/7975925/f3a42704-16b1-40f1-af95-249781ac9efc)
> 
> - Go to `Individual components`
> - Search for `MSVC v142`
> - Install the build tools (x64/x86)
> 
> ![image](https://github.com/gazzamc/starfield_hex_updater/assets/7975925/e19407b5-ba9d-431b-8d93-30c6903e70db)
> 
> - Re-try step 1 above again.

Let me know how that turns out.

**Comment by aurorarissime** [comment] 2023-11-09 08:26
Okay so:
- I didn't managed to get the .bat file running, so everytime I run it through cli.ps1 itself
- I got an error at the patching step again, [logfile_2023.11.09_09.19.48.log](https://github.com/gazzamc/starfield_hex_updater/files/13305651/logfile_2023.11.09_09.19.48.log)
- This is what I get, auto installer doesn't seem to change the commit, ![image](https://github.com/gazzamc/starfield_hex_updater/assets/121387740/32089385-a4bb-4751-9079-ef4311f44566)
- All of the above occured after I installed the exact VS component :')
- Also, it still only says C++ compiler found, not VS

**Comment by gazzamc** [comment] 2023-11-09 08:48
> Okay so:
> 
> * I didn't managed to get the .bat file running, so everytime I run it through cli.ps1 itself
> * I got an error at the patching step again, [logfile_2023.11.09_09.19.48.log](https://github.com/gazzamc/starfield_hex_updater/files/13305651/logfile_2023.11.09_09.19.48.log)
> * This is what I get, auto installer doesn't seem to change the commit, ![image](https://user-images.githubusercontent.com/121387740/281664921-32089385-a4bb-4751-9079-ef4311f44566.png)
> * All of the above occured after I installed the exact VS component :')
> * Also, it still only says C++ compiler found, not VS

You did install visual studio 2022? or is it a version below. It only looks for vs2022. It shouldn't matter anyway as it's finding a compiler. The main issue here is that it's not patching correctly and not patching the correct version of sfse. We can try do it manually to see if any errors pop up that may not be on the log.

Lets start fresh again, delete the `sfse` folder in the `starfield_hex_updater ` folder
1. Open powershell with admin privs
2. cd to the `starfield_hex_updater` folder
3. Run the following commands
- `git clone https://github.com/ianpatt/sfse.git`
- `cd sfse`
- `git checkout 2189c57`
4. Verify with `git branch`

If it's all good we can proceed with the patching. Continuing from above in the same window.

1. Run `cd ..` to return to `starfield_hex_updater` folder
2. Run the following commands:
- `python hex_updater.py -m patch -p sfse`
- `python hex_updater.py -m update -p sfse/sfse -d hex_tables/hex_table_1.7.36_2189c57.json`

Try and build:

1. `cmake -B sfse\build -S sfse`
2. `cmake --build sfse\build --config Release`

Verify the files are in `sfse\build\sfse\Release` & `sfse\build\sfse_loader\Release`

**Comment by gazzamc** [comment] 2023-11-09 08:52
I was able to reproduce your other error above 

`
Traceback (most recent call last):mpleted. (Number of bytes processed: 5282424) ]
File "G:\SFSE\starfield_hex_updater\hex_updater.py", line 389, in 6) ]
main(sys.argv[1:])
File "G:\SFSE\starfield_hex_updater\hex_updater.py", line 360, in main
hex_dict = get_dict(dict_file_name)
^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\SFSE\starfield_hex_updater\hex_updater.py", line 136, in get_dict
with open(r'{}'.format(path), 'r') as file:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
`

It was due to the path to `sfse` pointing to the root of the repo and not the `sfse` folder containing the files for the dll eg. `/sfse` vs `/sfse/sfse`.

Unfortunately I can't do much about that as that's how to repo is structured.

Edit: 
I've just seen you're using PS 7+, I have not tested it on this version. I wrote and tested it on PS 5+ as that was pre-installed on my system. I'll update it later and see if I have a similar issue with the auto installer.

**Comment by aurorarissime** [comment] 2023-11-09 09:15
> > Okay so:
> > 
> > * I didn't managed to get the .bat file running, so everytime I run it through cli.ps1 itself
> > * I got an error at the patching step again, [logfile_2023.11.09_09.19.48.log](https://github.com/gazzamc/starfield_hex_updater/files/13305651/logfile_2023.11.09_09.19.48.log)
> > * This is what I get, auto installer doesn't seem to change the commit, ![image](https://user-images.githubusercontent.com/121387740/281664921-32089385-a4bb-4751-9079-ef4311f44566.png)
> > * All of the above occured after I installed the exact VS component :')
> > * Also, it still only says C++ compiler found, not VS
> 
> You did install visual studio 2022? or is it a version below. It only looks for vs2022. It shouldn't matter anyway as it's finding a compiler. The main issue here is that it's not patching correctly and not patching the correct version of sfse. We can try do it manually to see if any errors pop up that may not be on the log.
> 
> Lets start fresh again, delete the `sfse` folder in the `starfield_hex_updater ` folder
> 
> 1. Open powershell with admin privs
> 2. cd to the `starfield_hex_updater` folder
> 3. Run the following commands
> 
> * `git clone https://github.com/ianpatt/sfse.git`
> * `cd sfse`
> * `git checkout 2189c57`
> 
> 4. Verify with `git branch`
> 
> If it's all good we can proceed with the patching. Continuing from above in the same window.
> 
> 1. Run `cd ..` to return to `starfield_hex_updater` folder
> 2. Run the following commands:
> 
> * `python hex_updater.py -m patch -p sfse`
> * `python hex_updater.py -m update -p sfse/sfse -d hex_tables/hex_table_1.7.36_2189c57.json`
> 
> Try and build:
> 
> 1. `cmake -B sfse\build -S sfse`
> 2. `cmake --build sfse\build --config Release`
> 
> Verify the files are in `sfse\build\sfse\Release` & `sfse\build\sfse_loader\Release`

Honestly I don't know which solution we tried but this worked. I have the dll and the exe, got no errors, works like a charm!

**Comment by gazzamc** [comment] 2023-11-09 09:30
I think it's related to the powershell version and using non powershell commands, I can look into this and test with a newer version of powershell.

There was a few issues:
- The repo not switching to the correct commit
- The patch script not patching correctly (probably related to the above) 
- The batch file not working on PS7+
- Maybe an incompatibility issue with vs17 tools? 
- I need to update the manual patch instructions, the path may be mistaking for the root 

The above list is a checklist for me btw 😅

Thanks for bringing this to my attention. On the bright side this is the hardest part of the process, everything else should be trivial.

**Comment by gazzamc** [comment] 2023-11-09 22:12
> I think it's related to the powershell version and using non powershell commands, I can look into this and test with a newer version of powershell.
> 
> There was a few issues:
> 
> * ~~The repo not switching to the correct commit~~
> * ~~The patch script not patching correctly (probably related to the above)~~
> * ~~The batch file not working on PS7+~~
> * ~~Maybe an incompatibility issue with vs17 tools?~~
> * ~~I need to update the manual patch instructions, the path may be mistaking for the root~~
> 
> The above list is a checklist for me btw 😅
> 
> Thanks for bringing this to my attention. On the bright side this is the hardest part of the process, everything else should be trivial.

@Alixxx-please I've updated the script to work with PS7, if you get the chance to test it that would be great. I've done some testing on my own systems and the auto installer seems to work fine from install to build.

Many of your issues were a result of the script spawning powershell 5+ which didn't have the restriction removed, on top of that there seemed to be some differences in my logic for obtaining the commit ID which is why it didn't switch to the branch or even patch correctly (as retrieving the dictionary filename used a similar method).

I'll close this issue now as it's resolved, but if you run into any issues don't hesitate to open another.

**Closed as completed by gazzamc** 2023-11-09 22:12 UTC

**Comment by aurorarissime** [comment] 2023-11-10 10:12
Thanks you for fixing the problems and for your help!
- First of all I can double click on run_ps7.bat and it launches the script as intented, with the first time message for the game path etc.
- The compiler seems to find VS2022..? At least it found something more than last time .
![image](https://github.com/gazzamc/starfield_hex_updater/assets/121387740/6b89feaf-4370-4f43-b3ef-3c6ed137eda1)
- Cloning and changing head work, even though git's message is overlaping your menu.
![image](https://github.com/gazzamc/starfield_hex_updater/assets/121387740/f2a137e1-d068-48e3-a9c3-7f7102b76ae4)
- Patching works like a charm, instant an without any error message!
- Building is also working, outputs the .dll and .exe. But even after a long time, the screen doesn't change even though looking at the logs, both files are built. I had to close and reopen the script to get to the next step, moving files.
![image](https://github.com/gazzamc/starfield_hex_updater/assets/121387740/c1396d96-5205-4ab8-8297-b06a45584568)

- It also correctly moves the files into the new game path, and sfse works when playing Starfield through sfse_loader.exe!
Here are the logs, in case you want to check for details :)
[logfile_2023.11.10_10.55.07.log](https://github.com/gazzamc/starfield_hex_updater/files/13318101/logfile_2023.11.10_10.55.07.log)

**Comment by gazzamc** [comment] 2023-11-10 15:00
> Thanks you for fixing the problems and for your help!

No problem, I wasn't aware of the different versions of powershell before this issue, so it's good that it can atleast function now on powershell 7.

> 
> * First of all I can double click on run_ps7.bat and it launches the script as intented, with the first time message for the game path etc.
> * The compiler seems to find VS2022..? At least it found something more than last time .
>   ![image](https://user-images.githubusercontent.com/121387740/282024781-6b89feaf-4370-4f43-b3ef-3c6ed137eda1.png)

The compiler is the most important here, I will probably remove the check for vs2022 later as it's not really needed. This also removes the need for `vswhere.exe`, so one less dependency.

> * Cloning and changing head work, even though git's message is overlaping your menu.
>   ![image](https://user-images.githubusercontent.com/121387740/282025078-f2a137e1-d068-48e3-a9c3-7f7102b76ae4.png)

After a bit of research there seems to be a visual bug with the network request not clearing, causing issues with the text. I'll see if I can improve it, but for now it can stay ugly if it works.

> * Patching works like a charm, instant an without any error message!

Perfect!

> * Building is also working, outputs the .dll and .exe. But even after a long time, the screen doesn't change even though looking at the logs, both files are built. I had to close and reopen the script to get to the next step, moving files.
>   ![image](https://user-images.githubusercontent.com/121387740/282026236-c1396d96-5205-4ab8-8297-b06a45584568.png)

This is a bug that also happens on PS5, I've been looking into a solution but it's still WIP.

> * It also correctly moves the files into the new game path, and sfse works when playing Starfield through sfse_loader.exe!
>   Here are the logs, in case you want to check for details :)
>   [logfile_2023.11.10_10.55.07.log](https://github.com/gazzamc/starfield_hex_updater/files/13318101/logfile_2023.11.10_10.55.07.log)

That's great to here it's working as intended, I was a bit worried about the game exe not moving as it's using PS5, PS7 wouldn't work with the executable I'm using to bypass the permissions issue. It shouldn't be an issue until windows stops shipping with PS5 (so probably never as sfse would surely support gamepass by then :)).

Once again, Appreciate the feedback.
